---

namespace: 'ansibleguy'
name: 'opnsense'
version: 1.2.12
readme: 'README.md'
authors:
  - 'AnsibleGuy <guy@ansibleguy.net>'
description: "Ansible Collection to manage OPNSense firewalls using their API"
license_file: 'LICENSE.txt'
tags:
  - 'firewall'
  - 'api'
  - 'opnsense'
  - 'iac'
  - 'network'
  - 'security'
  - 'filter'
dependencies: {}
repository: 'https://github.com/ansibleguy/collection_opnsense'
documentation: 'https://opnsense.ansibleguy.net'
homepage: 'https://www.o-x-l.com'
issues: 'https://github.com/ansibleguy/collection_opnsense/issues'
build_ignore: []
